#pragma checksum "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\DataModelsTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ebe26cd10c1daae9c15aa725462d27559f8241fb"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.DataModelsTemplate), @"default", @"/DataModelsTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ebe26cd10c1daae9c15aa725462d27559f8241fb", @"/DataModelsTemplate.cs.vtt")]
    public class DataModelsTemplate : IVySoft.VPlatform.Target.ModelCode.Xml.Serialization.DataModelContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\DataModelsTemplate.cs.vtt"
  
	foreach(var module in Model.Modules)
	{
		if(!module.IsExternal)
		{
			var folder = System.IO.Path.Combine(Options.OutputFolder, module.Namespace + ".Xml.Serialization");
			System.IO.Directory.CreateDirectory(folder);

			foreach(var type in module.Types)
			{
				if(type is IVySoft.VPlatform.Target.ModelCode.EntityType)
				{
					Generate_EntityType(module, (IVySoft.VPlatform.Target.ModelCode.EntityType)type, System.IO.Path.Combine(folder, type.Name + ".cs"));
				}
			}
		}
	}

#line default
#line hidden
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
