#pragma checksum "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ca77a35940103659e9e5786dd97d9fae2ba92a2a"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.EntityTypeTemplate), @"default", @"/EntityTypeTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
#line 2 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
using System.Linq;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ca77a35940103659e9e5786dd97d9fae2ba92a2a", @"/EntityTypeTemplate.cs.vtt")]
    public class EntityTypeTemplate : IVySoft.VPlatform.Target.ModelCode.Xml.Serialization.EntityTypeContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("using System.Collections.Generic;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\nusing System.Xml.Serialization;\r\nusing System.Linq;\r\n\r\nnamespace ");
#line 9 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
     Write(Module.Namespace);

#line default
#line hidden
#line 9 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                      Write();

#line default
#line hidden
            WriteLiteral(".Xml.Serialization\r\n{\r\n    [XmlRoot(Namespace = XmlConfig.Namespace)]\r\n    public class ");
#line 12 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral("\r\n    {\r\n");
#line 14 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[XmlElement()]\r\n\t\t");
            WriteLiteral("public ");
#line 17 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(property.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 17 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                           Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 18 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 20 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 22 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArray()]\r\n\t\t");
            WriteLiteral("public ");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral("[] ");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                        Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 26 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 26 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 29 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 31 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArray()]\r\n\t\t");
            WriteLiteral("public ");
#line 34 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral("[] ");
#line 34 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                       Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 35 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 35 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n\t\tpublic ");
#line 38 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
          Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 38 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                            Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral(" ToModel()\r\n        {\r\n            return new ");
#line 40 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                  Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 40 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                    Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral("\r\n            {\r\n");
#line 42 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             foreach(var property in EntityType.Properties)
			{
				if(property.ResolvedType.Kind == "Primitive")
				{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
#line 46 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(property.Name);

#line default
#line hidden
            WriteLiteral(" = this.");
#line 46 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                   Write(property.Name);

#line default
#line hidden
            WriteLiteral(",\r\n");
#line 47 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
				}
				else
				{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
#line 50 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(property.Name);

#line default
#line hidden
            WriteLiteral(" = this.");
#line 50 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                   Write(property.Name);

#line default
#line hidden
#line 50 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                 Write();

#line default
#line hidden
            WriteLiteral("?.ToModel(),\r\n");
#line 51 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
				}
			}

#line default
#line hidden
            WriteLiteral("\t\t");
#line 53 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 55 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
     Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" = new List<");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                           Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                             Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(">((this.");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                            Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" == null) ? new ");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                      Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                        Write(association.Right.Type);

#line default
#line hidden
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                               Write();

#line default
#line hidden
            WriteLiteral("[0] : this.");
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                           Write(association.Left.Property);

#line default
#line hidden
#line 57 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                     Write();

#line default
#line hidden
            WriteLiteral(".Select(x => x.ToModel())),\r\n");
#line 58 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 58 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\t\t");
#line 60 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 62 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
     Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" = new List<");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                            Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                              Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(">((this.");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                            Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" == null) ? new ");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                       Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                         Write(association.Left.Type);

#line default
#line hidden
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                               Write();

#line default
#line hidden
            WriteLiteral("[0] : this.");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                           Write(association.Right.Property);

#line default
#line hidden
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                      Write();

#line default
#line hidden
            WriteLiteral(".Select(x => x.ToModel())),\r\n");
#line 65 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 65 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("            };\r\n        }\r\n\r\n    }\r\n}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
