#pragma checksum "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "53abc9a36cdf674b09287a4287ee242e542e901c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.EntityTypeTemplate), @"default", @"/EntityTypeTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
#line 2 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
using System.Linq;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"53abc9a36cdf674b09287a4287ee242e542e901c", @"/EntityTypeTemplate.cs.vtt")]
    public class EntityTypeTemplate : IVySoft.VPlatform.Target.ModelCode.Xml.Serialization.EntityTypeContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("using System.Collections.Generic;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\nusing System.Xml.Serialization;\r\nusing System.Linq;\r\n\r\nnamespace ");
#line 9 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
     Write(Module.Namespace);

#line default
#line hidden
#line 9 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                      Write();

#line default
#line hidden
            WriteLiteral(".Xml.Serialization\r\n{\r\n    [XmlRoot(Namespace = XmlConfig.Namespace)]\r\n    public class ");
#line 12 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(EntityType.Name);

#line default
#line hidden
#line 12 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                             Write((EntityType.ResolvedBaseType == null) ? "" : (" : " + EntityType.ResolvedBaseType.Module.Namespace + ".Xml.Serialization." + EntityType.ResolvedBaseType.Name));

#line default
#line hidden
            WriteLiteral("\r\n    {\r\n");
#line 14 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{
			

#line default
#line hidden
#line 16 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(!property.XmlIgnore)
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[XmlElement()]\r\n\t\t");
            WriteLiteral("public ");
#line 19 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(property.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 19 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                           Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 20 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 20 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 23 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 25 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArray()]\r\n");
#line 28 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var derived in DerivedTypes(association.Right.ResolvedType))
		{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArrayItem(ElementName = \"");
#line 30 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                  Write(derived.Name);

#line default
#line hidden
            WriteLiteral("\", Type = typeof(");
#line 30 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                 Write(derived.Module.Namespace + ".Xml.Serialization." + derived.Name);

#line default
#line hidden
            WriteLiteral("))]\r\n");
#line 31 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
		}

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 32 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral("[] ");
#line 32 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                        Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 33 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 33 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 36 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 38 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArray()]\r\n");
#line 41 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var derived in DerivedTypes(association.Left.ResolvedType))
		{

#line default
#line hidden
            WriteLiteral("        ");
            WriteLiteral("[XmlArrayItem(ElementName = \"");
#line 43 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                  Write(derived.Name);

#line default
#line hidden
            WriteLiteral("\", Type = typeof(");
#line 43 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                 Write(derived.Module.Namespace + ".Xml.Serialization." + derived.Name);

#line default
#line hidden
            WriteLiteral("))]\r\n");
#line 44 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
		}

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 45 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral("[] ");
#line 45 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                       Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 46 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 46 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n\t\tpublic ");
#line 49 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
           Write((EntityType.ResolvedBaseType == null) ? "virtual" : "override");

#line default
#line hidden
            WriteLiteral(" object ToModel()\r\n\t\t{\r\n\t\t\tvar result = new ");
#line 51 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                        Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 51 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                           Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral("();\r\n\t\t\tthis.InitModel(result);\r\n\t\t\treturn result;\r\n\t\t}\r\n\r\n\t\tprotected void InitModel(");
#line 56 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                            Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 56 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                              Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral(" result)\r\n\t\t{\r\n");
#line 58 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(EntityType.ResolvedBaseType != null)
			{

#line default
#line hidden
            WriteLiteral("\t\t\t");
            WriteLiteral("base.InitModel(result);\r\n");
#line 61 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 63 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             foreach(var property in EntityType.Properties)
			{
				if(!property.XmlIgnore)
				{
					if(property.ResolvedType is IVySoft.VPlatform.Target.ModelCode.PrimitiveType)
					{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
            WriteLiteral("result.");
#line 69 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                    Write(property.Name);

#line default
#line hidden
            WriteLiteral(" = this.");
#line 69 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                          Write(property.Name);

#line default
#line hidden
            WriteLiteral(";\r\n");
#line 70 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
					}
					else
					{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
            WriteLiteral("result.");
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                    Write(property.Name);

#line default
#line hidden
            WriteLiteral(" = (");
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                      Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral(")this.");
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                           Write(property.Name);

#line default
#line hidden
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                         Write();

#line default
#line hidden
            WriteLiteral("?.ToModel();\r\n");
#line 74 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
					}
				}
			}

#line default
#line hidden
            WriteLiteral("\t\t");
#line 77 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 79 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("result.");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" = new List<");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                  Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                    Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(">((this.");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                   Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" == null) ? new ");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                             Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                               Write(association.Right.Type);

#line default
#line hidden
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                      Write();

#line default
#line hidden
            WriteLiteral("[0] : this.");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                  Write(association.Left.Property);

#line default
#line hidden
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                            Write();

#line default
#line hidden
            WriteLiteral(".Select(x => (");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                           Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                                             Write(association.Right.Type);

#line default
#line hidden
#line 81 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                                                                    Write();

#line default
#line hidden
            WriteLiteral(")x.ToModel()));\r\n");
#line 82 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 82 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\t\t");
#line 84 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 86 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("result.");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
            Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" = new List<");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                   Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                     Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(">((this.");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                   Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" == null) ? new ");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                              Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                Write(association.Left.Type);

#line default
#line hidden
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                      Write();

#line default
#line hidden
            WriteLiteral("[0] : this.");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                  Write(association.Right.Property);

#line default
#line hidden
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                             Write();

#line default
#line hidden
            WriteLiteral(".Select(x => (");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                            Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral(".");
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                                              Write(association.Left.Type);

#line default
#line hidden
#line 88 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
                                                                                                                                                                                                                                                                                    Write();

#line default
#line hidden
            WriteLiteral(")x.ToModel()));\r\n");
#line 89 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 89 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode.Xml.Serialization\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("        }\r\n    }\r\n}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
