#pragma checksum "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\DataModelsTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "b6f07309a87838904694d284939859a5951754ca"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.DataModelsTemplate), @"default", @"/DataModelsTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"b6f07309a87838904694d284939859a5951754ca", @"/DataModelsTemplate.cs.vtt")]
    public class DataModelsTemplate : IVySoft.VPlatform.Target.ModelCode.DataModelContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\DataModelsTemplate.cs.vtt"
  
	foreach(var module in Model.Modules)
	{
		var folder = System.IO.Path.Combine(Options.OutputFolder, module.Name + ".Model");
		System.IO.Directory.CreateDirectory(folder);

		foreach(var entity_type in module.Types)
		{
			Generate_EntityType(entity_type, System.IO.Path.Combine(folder, entity_type.Name + ".cs"));
		}
	}

#line default
#line hidden
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
