#pragma checksum "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\DataModelsTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2b9e3a36b39082b7e5acef11b404f3fd85b4d49e"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.DataModelsTemplate), @"default", @"/DataModelsTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
#line 2 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\DataModelsTemplate.cs.vtt"
using Microsoft.EntityFrameworkCore;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"2b9e3a36b39082b7e5acef11b404f3fd85b4d49e", @"/DataModelsTemplate.cs.vtt")]
    public class DataModelsTemplate : IVySoft.VPlatform.Target.ModelCode.DataModelContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 3 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\DataModelsTemplate.cs.vtt"
  
	foreach(var module in Model.Modules)
	{
		if(!module.IsExternal)
		{
			var folder = System.IO.Path.Combine(Options.OutputFolder, module.Namespace);
			System.IO.Directory.CreateDirectory(folder);

			foreach(var entity_type in module.Types)
			{
				Generate_EntityType(module, entity_type, System.IO.Path.Combine(folder, entity_type.Name + ".cs"));
			}
		}
	}

#line default
#line hidden
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
