#pragma checksum "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "25e1ba83b8a251d1aa240a04bf4fa03990a4fcd0"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.EntityTypeTemplate), @"default", @"/EntityTypeTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"25e1ba83b8a251d1aa240a04bf4fa03990a4fcd0", @"/EntityTypeTemplate.cs.vtt")]
    public class EntityTypeTemplate : IVySoft.VPlatform.Target.ModelCode.EntityTypeContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("using System.Collections.Generic;\r\n\r\nnamespace IVySoft.VPlatform.Target.ModelCode\r\n{\r\n    public class ");
#line 6 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral("\r\n    {\r\n\t    [Key]\r\n        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]\r\n        public int Id { get; set; }\r\n\r\n");
#line 12 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{
			

#line default
#line hidden
#line 14 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(property.Multiplicity != "0..*" && property.Multiplicity != "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
            WriteLiteral("public ");
#line 16 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(property.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 16 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                   Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 17 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 17 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 20 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{
			

#line default
#line hidden
#line 22 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(property.Multiplicity == "0..*" || property.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t\t\t");
            WriteLiteral("public virtual IList<");
#line 24 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                  Write(property.Type);

#line default
#line hidden
            WriteLiteral("> ");
#line 24 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                  Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("    }\r\n}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
