#pragma checksum "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "cf09d685b60bc04929de38f880ddd0a895e55615"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.EntityTypeTemplate), @"default", @"/EntityTypeTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
#line 2 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
using System.Linq;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"cf09d685b60bc04929de38f880ddd0a895e55615", @"/EntityTypeTemplate.cs.vtt")]
    public class EntityTypeTemplate : IVySoft.VPlatform.Target.ModelCode.EntityTypeContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("using System.Collections.Generic;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\n\r\nnamespace ");
#line 7 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
     Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral("\r\n{\r\n    public class ");
#line 9 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(EntityType.Name);

#line default
#line hidden
#line 9 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                             Write((EntityType.ResolvedBaseType == null) ? "" : (" : " + EntityType.ResolvedBaseType.FullName));

#line default
#line hidden
            WriteLiteral("\r\n    {\r\n");
#line 11 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         if(EntityType.ResolvedBaseType == null)
		{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[Key]\r\n\t\t");
            WriteLiteral("[DatabaseGenerated(DatabaseGeneratedOption.Identity)]\r\n\t\t");
            WriteLiteral("public int Id { get; set; }\r\n");
#line 16 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 18 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{
			if(property.ResolvedType is IVySoft.VPlatform.Target.ModelCode.PrimitiveType)
			{
				if(property.Nullable && @property.ResolvedType.FullName != "string")
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 24 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral("? ");
#line 24 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                             Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; } ");
#line 24 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                                           Write(string.IsNullOrWhiteSpace(property.Default) ? "" : "=" + property.Default);

#line default
#line hidden
            WriteLiteral("\r\n");
#line 25 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
				else
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 28 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral(" ");
#line 28 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                            Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; } ");
#line 28 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                                          Write(string.IsNullOrWhiteSpace(property.Default) ? "" : "=" + property.Default);

#line default
#line hidden
            WriteLiteral("\r\n");
#line 29 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 33 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(property.Name);

#line default
#line hidden
            WriteLiteral("))]\r\n");
#line 34 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				if(property.Nullable)
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public int? ");
#line 36 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                  Write(property.Name);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n");
#line 37 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
				else
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public int ");
#line 40 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(property.Name);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n");
#line 41 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public virtual ");
#line 42 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral(" ");
#line 42 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                    Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 43 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 46 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 48 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[InverseProperty(nameof(");
#line 50 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                             Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(".");
#line 50 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                     Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public virtual IList<");
#line 51 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                          Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral("> ");
#line 51 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                   Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 52 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 55 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public int ");
#line 56 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n\t\t");
            WriteLiteral("public virtual ");
#line 57 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 57 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                            Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 58 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 58 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 61 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 63 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[InverseProperty(nameof(");
#line 65 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                             Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(".");
#line 65 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                    Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public virtual IList<");
#line 66 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                          Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral("> ");
#line 66 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                  Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 67 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 70 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public int ");
#line 71 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n\t\t");
            WriteLiteral("public virtual ");
#line 72 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 72 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                           Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 73 "C:\Users\v.malyshev\source\repos\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("    }\r\n}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
