#pragma checksum "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "81f47b90fa7fe90b933bc21e1d308f745d7af1c2"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.EntityTypeTemplate), @"default", @"/EntityTypeTemplate.cs.vtt")]
namespace Razor
{
    #line hidden
#line 2 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
using System.Linq;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"81f47b90fa7fe90b933bc21e1d308f745d7af1c2", @"/EntityTypeTemplate.cs.vtt")]
    public class EntityTypeTemplate : IVySoft.VPlatform.Target.ModelCode.EntityTypeContext
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("using System.Collections.Generic;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing System.ComponentModel.DataAnnotations.Schema;\r\n\r\nnamespace ");
#line 7 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
     Write(Module.Namespace);

#line default
#line hidden
            WriteLiteral("\r\n{\r\n    public class ");
#line 9 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(EntityType.Name);

#line default
#line hidden
            WriteLiteral("\r\n    {\r\n\t    [Key]\r\n        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]\r\n        public int Id { get; set; }\r\n\r\n");
#line 15 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var property in EntityType.Properties)
		{
			if(property.ResolvedType.Kind == "Primitive")
			{
				if(property.Nullable && @property.ResolvedType.FullName != "string")
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 21 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral("? ");
#line 21 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                             Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; } ");
#line 21 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                                           Write(string.IsNullOrWhiteSpace(property.Default) ? "" : "=" + property.Default);

#line default
#line hidden
            WriteLiteral("\r\n");
#line 22 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
				else
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public ");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
            Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral(" ");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                            Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; } ");
#line 25 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                                          Write(string.IsNullOrWhiteSpace(property.Default) ? "" : "=" + property.Default);

#line default
#line hidden
            WriteLiteral("\r\n");
#line 26 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 30 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(property.Name);

#line default
#line hidden
            WriteLiteral("))]\r\n");
#line 31 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				if(property.Nullable)
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public int? ");
#line 33 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                  Write(property.Name);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n");
#line 34 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}
				else
				{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public int ");
#line 37 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(property.Name);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n");
#line 38 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
				}

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("public virtual ");
#line 39 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(property.ResolvedType.FullName);

#line default
#line hidden
            WriteLiteral(" ");
#line 39 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                    Write(property.Name);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 40 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 43 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Left.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 45 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(association.Left.Multiplicity == "0..*" || association.Left.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[InverseProperty(nameof(");
#line 47 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                             Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(".");
#line 47 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                     Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public virtual IList<");
#line 48 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                          Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral("> ");
#line 48 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                   Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 49 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 52 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public int ");
#line 53 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n\t\t");
            WriteLiteral("public virtual ");
#line 54 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(association.Right.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 54 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                            Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 55 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 55 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("\r\n");
#line 58 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
         foreach(var association in Module.Associations.Where(x => x.Right.Type == EntityType.Name))
		{
			

#line default
#line hidden
#line 60 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             if(association.Right.Multiplicity == "0..*" || association.Right.Multiplicity == "1..*")
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[InverseProperty(nameof(");
#line 62 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                             Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(".");
#line 62 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                    Write(association.Left.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public virtual IList<");
#line 63 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                          Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral("> ");
#line 63 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                                  Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 64 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}
			else
			{

#line default
#line hidden
            WriteLiteral("\t\t");
            WriteLiteral("[ForeignKey(nameof(");
#line 67 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                        Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("))]\r\n\t\t");
            WriteLiteral("public int ");
#line 68 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                 Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral("Id { get; set; }\r\n\t\t");
            WriteLiteral("public virtual ");
#line 69 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                    Write(association.Left.Type);

#line default
#line hidden
            WriteLiteral(" ");
#line 69 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
                                           Write(association.Right.Property);

#line default
#line hidden
            WriteLiteral(" { get; set; }\r\n");
#line 70 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
			}

#line default
#line hidden
#line 70 "C:\Users\User\projects\vplatform\src\targets\IVySoft.VPlatform.Target.ModelCode\EntityTypeTemplate.cs.vtt"
             
		}

#line default
#line hidden
            WriteLiteral("    }\r\n}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
